#!/bin/bash

NAME=$1
FS=$2
PASSWORD=$3
DF_COMMAND="df -Hl | grep $NAME | awk '{print \$1}'"
BLOCK_DEVICE_NAME=$(eval "$DF_COMMAND")
sudo diskutil unmount $BLOCK_DEVICE_NAME
sudo mkdir -p /Volumes/$NAME
echo "Creating dir: /Volumes/$NAME"
diskutil apfs unlockVolume $BLOCK_DEVICE_NAME -passphrase "$PASSWORD" -nomount

echo "sudo mount -t $FS $BLOCK_DEVICE_NAME /Volumes/$NAME"
sudo mount -t $FS $BLOCK_DEVICE_NAME /Volumes/$NAME
echo "mount -t $FS on: /Volumes/$NAME"